import * as schema from "~/server/db/schema";

type ItemType = typeof schema.itemType.$inferSelect;

export const itemTypes: ItemType[] = [
  {
    name: "Fruiting Bed",
    id: "fruiting_bed",
    slug: "fruiting_bed",
    description: null,
    category: "biological",
    trackLineage: true,
    defaultUom: "each",
    icon: "box",
    color: null,
    config: null,
  },
  {
    name: "Boxed Mushrooms",
    id: "boxed_mushrooms",
    slug: "boxed_mushrooms",
    description: null,
    category: "product",
    trackLineage: true,
    defaultUom: "lb",
    icon: "box",
    color: null,
    config: null,
  },
  {
    name: "Harvested Mushrooms",
    id: "harvested_fruit",
    slug: "harvested_fruit",
    description: null,
    category: "product",
    trackLineage: true,
    defaultUom: "g",
    icon: "mushroom",
    color: null,
    config: null,
  },
  {
    name: "Dried Mushrooms",
    id: "dried_product",
    slug: "dried_product",
    description: null,
    category: "product",
    trackLineage: true,
    defaultUom: "g",
    icon: "leaf",
    color: null,
    config: null,
  },
  {
    name: "Packed Case",
    id: "packed_good",
    slug: "packed_good",
    description: null,
    category: "product",
    trackLineage: true,
    defaultUom: "g",
    icon: "seed",
    color: null,
    config: null,
  },
  {
    name: "Skid / Pallet",
    id: "skid",
    slug: "skid",
    description: null,
    category: "logistics",
    trackLineage: true,
    defaultUom: "each",
    icon: "truck",
    color: null,
    config: null,
  },
];

export const operationTypes = [
  [
    // Mushroom operations
    {
      name: "Inoculate Plates",
      id: "plate_inoculation",
      slug: "plate_inoculation",
      description: "Inoculate agar plates from syringe or liquid culture",
      sortOrder: 10,
    },
    {
      name: "Inoculate LC",
      id: "lc_inoculation",
      slug: "lc_inoculation",
      description: "Inoculate liquid culture from syringe or plate",
      sortOrder: 15,
    },
    {
      name: "Transfer Culture",
      id: "plate_transfer",
      slug: "plate_transfer",
      description: "Transfer culture from one plate to new plates",
      sortOrder: 20,
    },
    {
      name: "Inoculate Grain",
      id: "grain_inoculation",
      slug: "grain_inoculation",
      description: "Inoculate grain jars/bags from plate or LC",
      sortOrder: 30,
    },
    {
      name: "Grain to Grain",
      id: "grain_to_grain",
      slug: "grain_to_grain",
      description: "Transfer colonized grain to fresh grain",
      sortOrder: 35,
    },
    {
      name: "Spawn to Bulk",
      id: "spawning",
      slug: "spawning",
      description: "Mix grain spawn with bulk substrate to create blocks",
      sortOrder: 40,
    },
    {
      name: "Harvest",
      id: "harvest",
      slug: "harvest",
      description: "Harvest mushrooms from a fruiting block",
      sortOrder: 50,
    },
    {
      name: "Dry",
      id: "drying",
      slug: "drying",
      description: "Dehydrate fresh mushrooms",
      sortOrder: 55,
    },
  ],
];
