import * as schema from "~/server/db/schema";

type LotType = typeof schema.lotType.$inferSelect;

export const lotTypes: LotType[] = [
  {
    name: "Fruiting Bed",
    id: "fruiting_bed",
    description: null,
    category: "biological",
    quantityName: null,
    quantityDefaultUnit: "each",
    icon: "box",
    color: null,
    codePrefix: null,
    codeNextNumber: 1,
  },
  {
    name: "Boxed Mushrooms",
    id: "boxed_mushrooms",
    description: null,
    category: "product",
    quantityName: null,
    quantityDefaultUnit: "lb",
    icon: "box",
    color: null,
    codePrefix: null,
    codeNextNumber: 1,
  },
  {
    name: "Harvested Mushrooms",
    id: "harvested_fruit",
    description: null,
    category: "product",
    quantityName: null,
    quantityDefaultUnit: "g",
    icon: "mushroom",
    color: null,
    codePrefix: null,
    codeNextNumber: 1,
  },
  {
    name: "Dried Mushrooms",
    id: "dried_product",
    description: null,
    category: "product",
    quantityName: null,
    quantityDefaultUnit: "g",
    icon: "leaf",
    color: null,
    codePrefix: null,
    codeNextNumber: 1,
  },
  {
    name: "Packed Case",
    id: "packed_good",
    description: null,
    category: "product",
    quantityName: null,
    quantityDefaultUnit: "g",
    icon: "seed",
    color: null,
    codePrefix: null,
    codeNextNumber: 1,
  },
  {
    name: "Skid / Pallet",
    id: "skid",
    description: null,
    category: "logistics",
    quantityName: null,
    quantityDefaultUnit: "each",
    icon: "truck",
    color: null,
    codePrefix: null,
    codeNextNumber: 1,
  },
];

export const operationTypes = [
  [
    {
      name: "Inoculate Plates",
      id: "plate_inoculation",
      description: "Inoculate agar plates from syringe or liquid culture",
      sortOrder: 10,
    },
    {
      name: "Inoculate LC",
      id: "lc_inoculation",
      description: "Inoculate liquid culture from syringe or plate",
      sortOrder: 15,
    },
    {
      name: "Transfer Culture",
      id: "plate_transfer",
      description: "Transfer culture from one plate to new plates",
      sortOrder: 20,
    },
    {
      name: "Inoculate Grain",
      id: "grain_inoculation",
      description: "Inoculate grain jars/bags from plate or LC",
      sortOrder: 30,
    },
    {
      name: "Grain to Grain",
      id: "grain_to_grain",
      description: "Transfer colonized grain to fresh grain",
      sortOrder: 35,
    },
    {
      name: "Spawn to Bulk",
      id: "spawning",
      description: "Mix grain spawn with bulk substrate to create blocks",
      sortOrder: 40,
    },
    {
      name: "Harvest",
      id: "harvest",
      description: "Harvest mushrooms from a fruiting block",
      sortOrder: 50,
    },
    {
      name: "Dry",
      id: "drying",
      description: "Dehydrate fresh mushrooms",
      sortOrder: 55,
    },
  ],
];
